# Generated by Django 5.2.6 on 2025-10-16 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SessionApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="session",
            name="room",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le nom de la salle ne peut contenir que lettres et chiffres (pas de caractères spéciaux)",
                        regex="^[A-Za-zÀ-ÖØ-öø-ÿ0-9\\s]+$",
                    )
                ],
            ),
        ),
    ]
