# Generated by Django 5.2.6 on 2025-09-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                ("Conference_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("IA", "computer science & ia"),
                            ("SE", "Science & eng"),
                            ("Sc", "Social sciences"),
                        ],
                        max_length=255,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "Submission_id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("abstract", models.TextField()),
                ("keywords", models.TextField()),
                ("paper", models.FileField(upload_to="papers/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "submitted"),
                            ("under review", "under review"),
                            ("rejected", "rejected"),
                        ],
                        default="submitted",
                        max_length=50,
                    ),
                ),
                ("payed", models.BooleanField(default=False)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizinCommitte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "committe_role",
                    models.CharField(
                        choices=[
                            ("chair", "chair"),
                            ("co-chair", "co-chair"),
                            ("member", "member"),
                        ],
                        default="member",
                        max_length=255,
                    ),
                ),
                ("date_joined", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committess",
                        to="ConferenceApp.conference",
                    ),
                ),
            ],
        ),
    ]
