# Generated by Django 5.2.6 on 2025-10-16 15:09

import ConferenceApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConferenceApp", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="Submission_id",
            new_name="submission_id",
        ),
        migrations.RenameField(
            model_name="submission",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="conference",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(30, "attention")]
            ),
        ),
        migrations.AlterField(
            model_name="conference",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="le titre de la conférence doit contenir uniquement des lettres et espaces",
                        regex="^[A-Za-zÀ-ÖØ-öø-ÿ\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="keywords",
            field=models.TextField(validators=[ConferenceApp.models.maxi]),
        ),
        migrations.AlterField(
            model_name="submission",
            name="paper",
            field=models.FileField(
                upload_to="papers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"], message="doit etre .pdf"
                    )
                ],
            ),
        ),
    ]
