# Generated by Django 5.2.6 on 2025-10-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ConferenceApp",
            "0003_rename_submission_id_submission_submission_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="conference",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
