# Generated by Django 5.2.6 on 2025-10-16 15:09

import UserApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, validators=[UserApp.models.verifyemail]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="les noms et prénoms ne doivent contenir que des lettres (et éventuellement des espaces ou tirets) ",
                        regex="[a-zA-Z\\s-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="les noms et prénoms ne doivent contenir que des lettres (et éventuellement des espaces ou tirets) ",
                        regex="[a-zA-Z\\s-]+$",
                    )
                ],
            ),
        ),
    ]
